### ISSUE TITLE
how to deploy locally, not push to jina and deploy on jina

### ISSUE THREAD

**Issue by learningpro** [jina-ai/gptdeploy#19]
same as title

**Comment by florian-hoenicke** [comment]
Thanks for opening the issue, you can use:
```
gptdeploy run ...
```

make sure you updated to the latest version
```
pip install gptdeploy -U
```

**Comment by florian-hoenicke** [comment]
Is your issue solved?

**Comment by florian-hoenicke** [comment]
@learningpro :)

**Comment by florian-hoenicke** [comment]
This issue is now resolved. You can generate, run and deploy separately.
