### ISSUE TITLE
feat: simplify Dockerfile creation

### ISSUE THREAD

**Issue by RobertHH-IS** [jina-ai/gptdeploy#47]
Could you throw up the correct dockerfile to simplify build?

**Comment by florian-hoenicke** [comment]
Hi robert, so you mean that we provide a standard dockerfile that is used for every task?
I think you are right. We could come up with a good base image that solves many purposes and then iterate over it.
So it will only generate the dockerfile if some special libraries are needed.
Thanks for opening this issue
