### ISSUE TITLE
ImportError: cannot import name 'CallbackManager' from 'langchain.callbacks' 

### ISSUE THREAD

**Issue by Sassun** [jina-ai/gptdeploy#48]
I followed the installation steps and now I am trying to run this example:

`gptdeploy % gptdeploy generate \            
--description "The user writes something and gets a related deep compliment." \
--test "Given the word test a deep compliment is generated" \
--model gpt-4 \
--path microservice`

However, I get this error see below:

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/6351084/233864978-06de4b44-3b0c-4ec0-ad84-42fe646cf68e.png">

**Comment by florian-hoenicke** [comment]
hi, this problem exists because we no longer support python 3.7

**Comment by florian-hoenicke** [comment]
Oh wait a second, you are using 3.10. I have to look into it
can you upgrade langchain?

**Comment by Sassun** [comment]
Upgraded langchain, now it works. Thanks!
