### ISSUE TITLE
Unable to deploy to jina cloud even though account has enough credits.

### ISSUE THREAD

**Issue by Sassun** [jina-ai/gptdeploy#50]
GPTDeploy successfully created a microservice, when I try to deploy it to the jina cloud I get an error message that states that I ran out of credits but I have still more than 1.3k credits in my jina account.

Flow ID: gptdeploy-e41ab756a8

![image](https://user-images.githubusercontent.com/6351084/233869856-ff72b472-ba56-43f1-9977-bafc9df7213f.png)

**Comment by joschkabraun** [comment]
Hi @Sassun thank you for raising this issue! We are currently looking into it.

**Comment by joschkabraun** [comment]
@Sassun do you mind sharing the files from the last trial of GPT Deploy to simplify bugging?

**Comment by Sassun** [comment]
Sure, here is the zip of the generated files for the microservice:

[ProductCompetitorSearchExecutor7290251.zip](https://github.com/jina-ai/gptdeploy/files/11309386/ProductCompetitorSearchExecutor7290251.zip)
