### ISSUE TITLE
gptdeploy run --path, running locally creates an error 

### ISSUE THREAD

**Issue by classimo69** [jina-ai/gptdeploy#52]
I have an error when running `gptdeploy run --path`

I've made sure docker is running, and this is the output

`Run a jina flow locally
⠴ Waiting missionprofilegeneratorexecutor3709634 gateway... ━━━━━━━━ 0/2 0:00:00The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
⠏ Waiting missionprofilegeneratorexecutor3709634... ━━━━━━━━╺━━━━━━━ 1/2 0:00:00The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
⠦ Waiting missionprofilegeneratorexecutor3709634... ━━━━━━━━╺━━━━━━━ 1/2 0:00:34`

**Comment by joschkabraun** [comment]
Hi @classimo69, happy to hear that you gave GPT Deploy a spin!

I just tried it locally with a different micro service and couldn't reproduce it. Do you mind sharing the files from the latest files such that I can easier debug the issue?

**Comment by classimo69** [comment]
I apologise @joschkabraun , could you elaborate which files you would like? the entire work folder for the latest iteration GPTdeploy generate made?

**Comment by joschkabraun** [comment]
Yes, the entire folder of the last iteration would be perfect!

**Comment by classimo69** [comment]
Here's the latest; I've had to share it in google drive:

https://drive.google.com/drive/folders/1-5zg7bkqAKW2IsJPn0vZI_83Ddfi0Cqb?usp=sharing

**Comment by joschkabraun** [comment]
Great, I just request access to it!

**Comment by joschkabraun** [comment]
Thank you for sharing! I just checked the actual code and GPT Deploy wasn't actually done with its iterations but only tricked the test in Docker.

We are currently working on a fix that this won't happen again in this PR: https://github.com/jina-ai/gptdeploy/pull/65
