### ISSUE TITLE
Import error: Cannot import CallbackManager

### ISSUE THREAD

**Issue by benjwolff** [jina-ai/gptdeploy#77]
Hi,

I wanted to try out gptdeploy. Nevertheless, wenn running gptdeploy, Python throws an ImportError.
I tried several Python-Versions (3.8, 3.10, 3.11) and on another computer, but in any case I got the same error.

Here is the error message:

```
Traceback (most recent call last):
  File "/home/XXX/software/miniconda3/envs/gptdeploy_test/bin/gptdeploy", line 5, in <module>
    from src import main
  File "/home/XXX/software/miniconda3/envs/gptdeploy_test/lib/python3.8/site-packages/src/__init__.py", line 3, in <module>
    from src.cli import main
  File "/home/XXX/software/miniconda3/envs/gptdeploy_test/lib/python3.8/site-packages/src/cli.py", line 7, in <module>
    from src.apis.gpt import configure_openai_api_key
  File "/home/XXX/software/miniconda3/envs/gptdeploy_test/lib/python3.8/site-packages/src/apis/gpt.py", line 8, in <module>
    from langchain.callbacks import CallbackManager
ImportError: cannot import name 'CallbackManager' from 'langchain.callbacks' (/home/XXX/software/miniconda3/envs/gptdeploy_test/lib/python3.8/site-packages/langchain/callbacks/__init__.py)
```

Thanks
Benjamin

**Comment by joschkabraun** [comment]
Hi, nice that you gave GPT Deploy a try!
What is your `langchain` version? We fixed it to `langchain==0.0.153` (https://github.com/jina-ai/gptdeploy/blob/main/requirements.txt#L8) on `main`

**Comment by benjwolff** [comment]
Hi Joschka,

thanks for answering. I installed GPT Deploy via `pip install gptdeploy` in a dedicated Conda environment.
This is installs `langchain==0.0.157`.

**Comment by joschkabraun** [comment]
Okay, can you try out `langhchain==0.0.157`?

**Comment by benjwolff** [comment]
I forced reinstallation from `langchain==0.0.157` to `langchain==0.0.153` via `pip install --force-reinstall -v "langchain==0.0.153"` . Now the ImportError has gone. Many thanks!
Anyhow installing via pip should install a compatible version of langchain.

**Comment by joschkabraun** [comment]
I agree. I will make a release. Thank you for pointing this out!
